server {
    listen 80;
    listen [::]:80;
    server_name sorting.samdpi.uz www.sorting.samdpi.uz;

    location = /favicon.ico {
        access_log off; log_not_found off;
    }
    location /static/ {
        root /home/ali/sorting/;
    }

    location /media/ {
        root /home/ali/sorting/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/sorting.sock;
    }
}