# Generated by Django 6.0.3 on 2026-03-17 05:29

import ckeditor_uploader.fields
import django.db.models.deletion
import tests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_a', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_b', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_c', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_d', ckeditor_uploader.fields.RichTextUploadingField()),
                ('correct', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha'), ('tj', 'Tojikcha'), ('fr', 'Fransuzcha'), ('de', 'Nemischa')], max_length=20)),
                ('is_additional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.JSONField(blank=True, default=tests.models.json, null=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='result_questions', to='tests.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.specialist'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=60)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('is_ended', models.BooleanField(default=False)),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.specialist')),
            ],
        ),
    ]
